### ISSUE TITLE
[Quest] Paladin - The Tome of Divinity - Dwarf

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#124]
After the initial quest for tome of divinity to speak to tiza battleforge you receive this follow-up quest that's lacking any quest text.

![d](http://puu.sh/ikVlG/0cfbe32981.jpg)

**Comment by GorbulasCrestfall** [comment]
I am unable to find any Quest Text associated with this Quest. Apparently it was intended, or overlooked by Blizzard at the time.

**Comment by AsuraDev** [comment]
This is rather weird. We have text that should be filling that after looking at the database. I'll look into it from core side, perhaps a bug with packets.

**Comment by AsuraDev** [comment]
Cancel that. I feel like an asshat. This is script related, same with Issue #108 (Dwarf version)

**Comment by AsuraDev** [comment]
Quest shouldn't even be used. This is Quest 1645, but 1646 is the one that starts the change. This looks like some random left over by Blizzard. Fixed and will be on test realm with the update later today.

**Comment by AsuraDev** [comment]
Solved this after two hours of messing with it. Going to explain it here for future reference.

Essentially, this is a special type of quest. there's actually 30 or 40 like it in the game.

It is a repeatable quest that is also Auto-Reward, meaning it should instantly show the completion screen to the player. On top of this, the quest is allowed to be redone UNTIL the follow up quest is done. In this case, the Auto-Reward grants you with the item "Tome of Divinity". When you gain the quest from the item, you lose access to this quest.

If you delete the item without finishing the quest, the quest then becomes Auto-Reward and available again. Once you've officially turned in the quest from the item, you lose access to the quest forever(as it should be, since it's no longer needed).

I implemented support for this based on the custom jadefire flags for Quests, and have it working. There is a quest in the Valley of Trials that also should use this quest, but I can't think of the name off the top of my head. I believe it's a shaman(or priest) quest.

Either way, this is fixed, and note of the cause is above. Closing this.
